# Generated by Django 5.2.6 on 2025-09-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_district_remove_order_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account_no',
            field=models.CharField(max_length=20, verbose_name='Card Number / PayPal Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.IntegerField(verbose_name='CVV / Transaction ID'),
        ),
    ]
